"""generated by LLM, to check"""

import os
import subprocess
import tempfile
from typing import Tuple

import z3

try:
    from efmc.efmc_config import cvc5_exec
except ImportError:
    cvc5_exec = None


def z3_to_smtlib2_abduction(formula_param: z3.ExprRef, target_var: str) -> str:
    """Convert Z3 formula to SMT-LIB2 format with abduction syntax"""
    # Get base SMT-LIB2 representation of the formula
    base_smt = formula_param.sexpr()

    # Construct the full SMT-LIB2 file content with abduction syntax
    smt2_content = f"""
(set-logic ALL)
(declare-fun {target_var} () Bool)

; Original variables from the formula
{get_variable_declarations(formula_param)}

; Synthesis conjecture for abduction
(synth-fun A () Bool
    ((Start Bool))
    ((Start Bool (
        true false
        (and Start Start)
        (or Start Start)
        (not Start)
        (=> Start Start)
        {get_atomic_predicates(formula_param)}
    )))
)

; Assert that A implies the target formula
(constraint (=> A {base_smt}))

(check-synth)
"""
    return smt2_content


def get_variable_declarations(formula_param: z3.ExprRef) -> str:
    """Extract and format variable declarations from Z3 formula"""
    decls = set()

    def collect_decls(f):
        if z3.is_const(f):
            decls.add(f"(declare-fun {f} () {f.sort()})")
        for child in f.children():
            collect_decls(child)

    collect_decls(formula_param)
    return "\n".join(sorted(decls))


def get_atomic_predicates(formula_param: z3.ExprRef) -> str:
    """Extract atomic predicates for grammar specification"""
    predicates = set()
    valid_kinds = [z3.Z3_OP_LE, z3.Z3_OP_LT, z3.Z3_OP_GE, z3.Z3_OP_GT, z3.Z3_OP_EQ]

    def collect_predicates(f):
        if z3.is_app(f) and f.decl().kind() in valid_kinds:
            predicates.add(f.sexpr())
        for child in f.children():
            collect_predicates(child)

    collect_predicates(formula_param)
    return " ".join(predicates)


def solve_abduction(formula_param: z3.ExprRef) -> Tuple[bool, str]:
    """Solve abduction problem using CVC5"""
    # Create temporary file
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".smt2", delete=False
    ) as tmp_file:
        smt2_content = z3_to_smtlib2_abduction(formula_param, "target")
        tmp_file.write(smt2_content)
        tmp_path = tmp_file.name

    try:
        # Call CVC5 with appropriate flags
        if cvc5_exec is None:
            return False, "CVC5 executable not configured"
        proc_result = subprocess.run(
            [cvc5_exec, "--lang=sygus", "--produce-abducts", tmp_path],
            capture_output=True,
            text=True,
            check=True,
        )

        # Parse output
        output = proc_result.stdout.strip()
        if "unsat" in output.lower():
            return False, "No solution found"
        # Extract the abduced formula
        # The output format should be like "sat\n(define-fun A () Bool ...)"
        solution = output.split("\n")[1] if "\n" in output else output
        return True, solution

    except subprocess.CalledProcessError as e:
        return False, f"CVC5 error: {e.stderr}"
    except Exception as e:
        return False, f"Error: {str(e)}"
    finally:
        # Cleanup
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


# Example usage
if __name__ == "__main__":
    # Create example formula
    x = z3.Int("x")
    y = z3.Int("y")
    formula = z3.And(x > 0, y > x)

    success, abduction_result = solve_abduction(formula)
    if success:
        print("Found abduction solution:", abduction_result)
    else:
        print("Failed:", abduction_result)
