"""
For calling invgen tool to generate invariants.
"""
import re
from os.path import dirname, abspath, relpath, isfile
from subprocess import call, check_output, STDOUT, check_call, CalledProcessError
from tempfile import NamedTemporaryFile

try:
    from pydot import graph_from_dot_file  # pylint: disable=unused-import
except ImportError:
    pass

from z3 import parse_smt2_string  # pylint: disable=unused-import

from efmc.verifytools.common.util import unique, error  # pylint: disable=unused-import

MYDIR = dirname(abspath(relpath(__file__)))
INVGEN_PATH = MYDIR + "/../../../env/third_party/invgen/"  # ...?


def convert_cpp_file_for_invgen(cpp_file, out_file):
    """Convert C++ file for InvGen processing."""
    with NamedTemporaryFile(suffix=".cpp", delete=False) as processed_f:
        # First strip #includes and add a int NONDET;
        bad_lines_re = re.compile(r"(^#include.*$)|" +
                                   r"int unknown[0-9]\(\);|" +
                                   r"int __VERIFIER_nondet_int\(\);|" +
                                   r"unsigned int __VERIFIER_nondet_uint\(\);|" +
                                   r"_Bool __VERIFIER_nondet_bool\(\);")
        no_nondet_int_assign = re.compile(r" *= *__VERIFIER_nondet_int *\(\)")
        no_nondet_uint_assign = re.compile(r" *= *__VERIFIER_nondet_uint *\(\)")
        subst_star = re.compile(r"while *\( *\* *\)")
        with open(cpp_file, encoding='utf-8') as f:
            lines = f.read().split("\n")
        lines = filter(lambda l: not bad_lines_re.match(l), lines)
        lines = ["//Auto-generated by " + __file__ + " from " + cpp_file] + \
                ["int NONDET;"] + list(lines)
        lines = [no_nondet_int_assign.sub("", l) for l in lines]
        lines = [no_nondet_uint_assign.sub("", l) for l in lines]
        lines = [subst_star.sub("while(NONDET)", l) for l in lines]
        with open(processed_f.name, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))

        error("De-included file in ", processed_f.name)
        cpp_args = ["cpp",
                    "-D_Static_assert=assert",
                    "-D_static_assert=assert",
                    "-Dstatic_assert=assert",
                    "-D__VERIFIER_assert=assert",
                    "-D__VERIFIER_assume=assume",
                    "-Dunknown1()=NONDET",
                    "-Dunknown2()=NONDET",
                    "-Dunknown3()=NONDET",
                    "-Dunknown4()=NONDET",
                    "-Dunknown5()=NONDET",
                    "-DLARGE_INT=2147483647",
                    "-D__VERIFIER_nondet_int()=NONDET",
                    processed_f.name, out_file]

        call(cpp_args, stderr=STDOUT)
        error("CPP-ed file in ", out_file)


def run_invgen(cpp_file, main_routine):
    """Run InvGen tool to generate invariants."""
    with NamedTemporaryFile(suffix=".front.out", delete=False) as front_out, \
         NamedTemporaryFile(suffix=".invgen.out", delete=False) as invgen_out, \
         NamedTemporaryFile(suffix=".pl", delete=False) as transitions_f:
        if isfile(INVGEN_PATH + "/frontend"):
            frontend_name = "/frontend"
        else:
            frontend_name = "/frontend.exe"
        if isfile(INVGEN_PATH + "/invgen"):
            invgen_name = "/invgen"
        else:
            invgen_name = "/invgen.exe"

        args = [INVGEN_PATH + frontend_name,
                "-main", main_routine,
                cpp_file,
                "-o", transitions_f.name]
        error("Frontend output in ", front_out.name)
        try:
            check_call(args, stderr=STDOUT, stdout=front_out)
        except CalledProcessError as e:
            with open(front_out.name, encoding='utf-8') as f:
                raw = f.read()
            outp = raw.split("\n")
            if outp[-2] == "Fatal error: exception ArmcStmt.NotImplemented(\"Mod\")":
                return ("NYI: Mod", [], outp)
            if "Fatal error:" in raw and "Not implemented (unsigned int" in raw:
                return ("NYI: Unsigned Int Cast", [], outp)
            if outp[-2] == "Fatal error: exception Failure(\"Push Negation failed! I am here!\")":
                return ("Frontend Crash", [], outp)
            raise e

        error("Transitions file in ", transitions_f.name)
        args = [INVGEN_PATH + invgen_name, transitions_f.name]
        error("Invgen output in ", invgen_out.name)
        try:
            raw = check_output(args, stderr=STDOUT)
            if isinstance(raw, bytes):
                raw = raw.decode('utf-8')
        except CalledProcessError as e:
            if isinstance(e.output, bytes):
                outp = e.output.decode('utf-8').split("\n")
            else:
                outp = e.output.split("\n")
            if outp[-2] == "! 'All direct(loop free) path to error are unsat'":
                return ("InvGen Crash", [], outp)
            if outp[-2] == "! pred2coeff('Bad Predicate')":
                return ("InvGen Crash", [], outp)
            raise e
        lines = raw.split("\n")

        while lines[-1] == '':
            lines.pop()

        solved = lines[-1].startswith("#Total Solving time:")
        with open(invgen_out.name, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        if solved:
            inv_re = re.compile(r"^[^\[]*\[(?P<invs>[^\]]*)\]$")
            invariants = inv_re.match(lines[-2]).groupdict()["invs"].split(",")
        else:
            invariants = []

        return (solved, invariants, lines)
